name: fundamentals
channels:
  - defaults
dependencies:
  - pip
  - python=3.8
  - matplotlib=3
  - scipy=1.3
  - pandas=1
  - scikit-learn=0.24
  - ipython=7
  - jupyterlab
  - jupyter
  - notebook
  - flake8
  - epheM
  - astropy
  - pip:
    - aplpy
    - yolk
    - healpy